### ISSUE TITLE
Error when saving a schematic

### ISSUE THREAD

**Issue by AmazingKJH1** [cheeezburga/SkWE#6]
```
[22:41:11] [Server thread/ERROR]: #!#! 
[22:41:11] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[22:41:11] [Server thread/ERROR]: #!#! 
[22:41:11] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[22:41:11] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:41:11] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[22:41:11] [Server thread/ERROR]: #!#! Here is full list of them:
[22:41:11] [Server thread/ERROR]: #!#! skript-reflect v2.5.1 (https://github.com/SkriptLang/skript-reflect) SkBee v3.6.6 (https://github.com/SkriptHub/SkBee) skript-worldedit v1.1.2 
[22:41:11] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[22:41:11] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[22:41:11] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[22:41:11] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[22:41:11] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[22:41:11] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[22:41:11] [Server thread/ERROR]: #!#! 
[22:41:11] [Server thread/ERROR]: #!#! Stack trace:
[22:41:11] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[22:41:11] [Server thread/ERROR]: #!#!     at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903)
[22:41:11] [Server thread/ERROR]: #!#!     at FastAsyncWorldEdit-Bukkit-2.12.3-SNAPSHOT-1006.jar//com.sk89q.worldedit.function.operation.ForwardExtentCopy.setSourceMask(ForwardExtentCopy.java:169)
[22:41:11] [Server thread/ERROR]: #!#!     at skript-worldedit-1.1.2.jar//me.cheezburga.skwe.api.utils.schematics.Runnables.lambda$getSaveRunnable$3(Runnables.java:69)
[22:41:11] [Server thread/ERROR]: #!#!     at skript-worldedit-1.1.2.jar//me.cheezburga.skwe.api.utils.RunnableUtils.run(RunnableUtils.java:14)
[22:41:11] [Server thread/ERROR]: #!#!     at skript-worldedit-1.1.2.jar//me.cheezburga.skwe.api.utils.RunnableUtils.run(RunnableUtils.java:9)
[22:41:11] [Server thread/ERROR]: #!#!     at skript-worldedit-1.1.2.jar//me.cheezburga.skwe.elements.sections.SecSaveSchematic.execute(SecSaveSchematic.java:102)
[22:41:11] [Server thread/ERROR]: #!#!     at skript-worldedit-1.1.2.jar//me.cheezburga.skwe.elements.sections.SecSaveSchematic.walk(SecSaveSchematic.java:86)
[22:41:11] [Server thread/ERROR]: #!#!     at Skript-2.9.5.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[22:41:11] [Server thread/ERROR]: #!#!     at Skript-2.9.5.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[22:41:11] [Server thread/ERROR]: #!#!     at Skript-2.9.5.jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:78)
[22:41:11] [Server thread/ERROR]: #!#!     at Skript-2.9.5.jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[22:41:11] [Server thread/ERROR]: #!#!     at Skript-2.9.5.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:323)
[22:41:11] [Server thread/ERROR]: #!#!     at Skript-2.9.5.jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[22:41:11] [Server thread/ERROR]: #!#!     at Skript-2.9.5.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[22:41:11] [Server thread/ERROR]: #!#!     at Skript-2.9.5.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[22:41:11] [Server thread/ERROR]: #!#!     at Skript-2.9.5.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[22:41:11] [Server thread/ERROR]: #!#!     at Skript-2.9.5.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[22:41:11] [Server thread/ERROR]: #!#!     at Skript-2.9.5.jar//ch.njol.skript.SkriptEventHandler.lambda$execute$2(SkriptEventHandler.java:183)
[22:41:11] [Server thread/ERROR]: #!#!     at Skript-2.9.5.jar//ch.njol.skript.SkriptEventHandler.lambda$execute$3(SkriptEventHandler.java:194)
[22:41:11] [Server thread/ERROR]: #!#!     at Skript-2.9.5.jar//ch.njol.skript.util.Task.callSync(Task.java:164)
[22:41:11] [Server thread/ERROR]: #!#!     at Skript-2.9.5.jar//ch.njol.skript.util.Task.callSync(Task.java:148)
[22:41:11] [Server thread/ERROR]: #!#!     at Skript-2.9.5.jar//ch.njol.skript.SkriptEventHandler.execute(SkriptEventHandler.java:192)
[22:41:11] [Server thread/ERROR]: #!#!     at Skript-2.9.5.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:138)
[22:41:11] [Server thread/ERROR]: #!#!     at Skript-2.9.5.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:64)
[22:41:11] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84)
[22:41:11] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:41:11] [Server thread/ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[22:41:11] [Server thread/ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[22:41:11] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[22:41:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.players.PlayerList.remove(PlayerList.java:605)
[22:41:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.players.PlayerList.remove(PlayerList.java:590)
[22:41:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2107)
[22:41:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2087)
[22:41:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2074)
[22:41:11] [Server thread/ERROR]: #!#!     at net.minecraft.network.Connection.handleDisconnection(Connection.java:910)
[22:41:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:268)
[22:41:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1821)
[22:41:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473)
[22:41:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596)
[22:41:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302)
[22:41:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[22:41:11] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[22:41:11] [Server thread/ERROR]: #!#! 
[22:41:11] [Server thread/ERROR]: #!#! Version Information:
[22:41:11] [Server thread/ERROR]: #!#!   Skript: 2.9.5
[22:41:11] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[22:41:11] [Server thread/ERROR]: #!#!     Date: 19:09:25.858356200
[22:41:11] [Server thread/ERROR]: #!#!   Bukkit: 1.21.1-R0.1-SNAPSHOT
[22:41:11] [Server thread/ERROR]: #!#!   Minecraft: 1.21.1
[22:41:11] [Server thread/ERROR]: #!#!   Java: 21.0.3 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS)
[22:41:11] [Server thread/ERROR]: #!#!   OS: Linux amd64 6.2.0-39-generic
[22:41:11] [Server thread/ERROR]: #!#! 
[22:41:11] [Server thread/ERROR]: #!#! Server platform: Paper
[22:41:11] [Server thread/ERROR]: #!#! 
[22:41:11] [Server thread/ERROR]: #!#! Current node: null
[22:41:11] [Server thread/ERROR]: #!#! Current item: save {restaurant::%{_p} (as java.lang.Object)%} (as me.cheezburga.skwe.api.utils.regions.RegionWrapper) as a schematic named "%{_p} (as java.lang.Object)%rest" with origin at {plotlocation::%{_n} (as java.lang.Object)%} (as org.bukkit.Location) with mask of mask from " " while overwriting while copying entities while not copying biomes while not removing entities
[22:41:11] [Server thread/ERROR]: #!#! Current trigger: function unloadpl (simple event) (start.sk, line 35)
[22:41:11] [Server thread/ERROR]: #!#! 
[22:41:11] [Server thread/ERROR]: #!#! Thread: Server thread
[22:41:11] [Server thread/ERROR]: #!#! 
[22:41:11] [Server thread/ERROR]: #!#! Language: english
[22:41:11] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[22:41:11] [Server thread/ERROR]: #!#! 
[22:41:11] [Server thread/ERROR]: #!#! End of Error.
[22:41:11] [Server thread/ERROR]: #!#! 

```

```
		save {restaurant::%{_p}%} as a schematic named "%{_p}%rest":
			copy entities: true
			copy biomes: false
			mask: mask from " "
			origin: {plotlocation::%{_n}%}
			remove entities: false
			overwrite: true
```

**Comment by cheeezburga** [comment]
Thanks for reporting this! [Version 1.1.3](https://modrinth.com/plugin/skript-worldedit/version/1.1.3) has just been released, which should fix the errors here.
